# Taps
tap "adoptopenjdk/openjdk"
tap "gcenx/wine"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "romkatv/powerlevel10k"

# Prerequisite casks
cask "xquartz"

# Brews
brew "argyll-cms"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "libtool"
brew "libyaml"
brew "openssl@1.1"
brew "readline"
brew "asdf"
brew "sqlite"
brew "xz"
brew "glib"
brew "bfg"
brew "carthage"
brew "chronograf"
brew "cmake"
brew "curl"
brew "dos2unix"
brew "pkg-config"
brew "f3"
brew "harfbuzz"
brew "lame"
brew "tesseract"
brew "freerdp"
brew "gcc"
brew "gh"
brew "libksba"
brew "gnupg"
brew "pango"
brew "gtk+3"
brew "smartmontools"
brew "gsmartcontrol"
brew "htop"
brew "hub"
brew "imagemagick"
brew "iperf3"
brew "ipmitool"
brew "jq"
brew "libksba"
brew "libxt"
brew "make"
brew "mas"
brew "neofetch"
brew "neovim"
brew "netcat"
brew "ocrmypdf"
brew "openconnect"
brew "pcre2"
brew "phoronix-test-suite"
brew "sox"
brew "speedtest-cli"
brew "telnet"
brew "tmux"
brew "unrar"
brew "wakeonlan"
brew "wget"
brew "winetricks"
brew "youtube-dl"
brew "zlib"
brew "zsh-autosuggestions"
brew "romkatv/powerlevel10k/powerlevel10k"

# Additional casks
cask "1password"
cask "adoptopenjdk"
cask "adoptopenjdk8"
cask "alfred"
cask "angry-ip-scanner"
cask "azure-data-studio"
cask "balenaetcher"
cask "bettertouchtool"
cask "bibdesk"
cask "bitbar"
cask "blackhole"
cask "calibre"
cask "carbon-copy-cloner"
cask "chromedriver"
cask "chronosync"
cask "dbeaver-community"
cask "devonthink"
cask "discord"
cask "displaycal"
cask "docker"
cask "dupeguru"
cask "font-firacode-nerd-font"
cask "geekbench"
cask "gfortran"
cask "github"
cask "gog-galaxy"
cask "google-backup-and-sync"
cask "google-chrome"
cask "handbrake"
cask "hex-fiend"
cask "intel-power-gadget"
cask "iterm2"
cask "key-codes"
cask "logitech-options"
cask "maciasl"
cask "mactex"
cask "menumeters"
cask "nextcloud"
cask "onedrive"
cask "openvpn-connect"
cask "osxfuse"
cask "pdfpenpro"
cask "plex"
cask "postman"
cask "rstudio"
cask "slack"
cask "sony-ps4-remote-play"
cask "spotify"
cask "steam"
cask "stellarium"
cask "synergy"
cask "tg-pro"
cask "veracrypt"
cask "visual-studio-code"
cask "vlc"
cask "vmware-fusion"
cask "wine-crossover"
cask "xnviewmp"
cask "yubico-authenticator"
cask "yubico-yubikey-manager"
cask "zoom"

# Mas List
mas "Affinity Designer", id: 824171161
mas "AwardWallet", id: 1473828829
mas "Byword", id: 420212497
mas "Deliveries", id: 290986013
mas "Discovery", id: 1381004916
mas "Disk Speed Test", id: 425264550
mas "Final Cut Pro", id: 424389933
mas "FruitJuice", id: 671736912
mas "Honey", id: 1472777122
mas "Marked 2", id: 890031187
mas "Media-Info", id: 550128418
mas "Messenger", id: 1480068668
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft To Do", id: 1274495053
mas "MindNode", id: 992076693
mas "Paprika Recipe Manager 3", id: 1303222628
mas "PhotoSweeper", id: 463362050
mas "Pocket", id: 568494494
mas "Rakuten Cash Back", id: 1451893560
mas "Reeder", id: 1449412482
mas "Spark", id: 1176895641
mas "Vimari", id: 1480933944
mas "Xcode", id: 497799835
